import { CRM_FEATURES, CRM_STAGES, CRM_STATS } from './crm.constants'
import { APP_URL } from './global'
import {
  AUTH_ROUTE_DASHBOARD,
  AUTH_ROUTE_DASHBOARD_EXAMPLE,
  AUTH_ROUTE_HOME,
  AUTH_ROUTE_LOGIN,
  AUTH_ROUTE_LOGIN_CREDENTIALS,
  AUTH_ROUTE_REGISTER,
  AUTH_ROUTE_RECOVERY,
  AUTH_ROUTE_VERIFY_EMAIL,
  AUTH_ROUTE_CREATE_PASSWORD,
  REMEMBER_EMAIL_STORAGE_KEY,
} from './auth.constants'

export {
  CRM_FEATURES,
  CRM_STAGES,
  CRM_STATS,
  APP_URL,
  REMEMBER_EMAIL_STORAGE_KEY,
  AUTH_ROUTE_LOGIN,
  AUTH_ROUTE_REGISTER,
  AUTH_ROUTE_LOGIN_CREDENTIALS,
  AUTH_ROUTE_RECOVERY,
  AUTH_ROUTE_VERIFY_EMAIL,
  AUTH_ROUTE_CREATE_PASSWORD,
  AUTH_ROUTE_DASHBOARD,
  AUTH_ROUTE_DASHBOARD_EXAMPLE,
  AUTH_ROUTE_HOME,
}
