import type { CrmFeature, CrmStage, CrmStat } from './frontpage/crm'
import type {
  AlertsCore,
  AuthCheckEmailResponse,
  AuthCreatePasswordPayload,
  AuthCreatePasswordForm,
  AuthForgotPasswordPayload,
  AuthForgotPasswordForm,
  AuthLoginErrorResponse,
  AuthPreLoginResponse,
  AuthLoginForm,
  AuthLoginPayload,
  AuthRegisterForm,
  AuthResendVerificationPayload,
  AuthResendVerificationForm,
  AuthRegisterPayload,
  PasswordRequirement,
  AuthVerifyEmailForm,
  AuthVerifyEmailResponse,
  AuthVerifyEmailPayload,
  AuthUser,
  ModulePermission,
} from './auth/auth.interface'
import type {
  SettingDeviceSession,
  SettingMfaDisablePayload,
  SettingMfaSetupData,
  SettingMfaSetupPayload,
  SettingMfaState,
  SettingTabKey,
  SettingTabOption,
  SettingMfaVerifyPayload,
  SettingUpdateAvatarForm,
  SettingUpdateAvatarPayload,
  SettingUpdateProfileForm,
  SettingUpdateProfilePayload,
} from './settings/setting.interface'
import type {
  IncomingNotificationPayload,
  NotificationApiItem,
  NotificationPagedFilters,
  NotificationCountResponse,
  NotificationConnectionStatus,
  NotificationPagedResponse,
  NotificationItem,
  NotificationVariant,
} from './notification/notification.interface'
import type {
  ValidationOptions,
  ValidationRule,
  ValidationTrigger,
} from './validation/validation.interface'

export type {
  CrmFeature,
  CrmStage,
  CrmStat,
  AuthLoginPayload,
  AuthRegisterForm,
  AuthRegisterPayload,
  SettingUpdateProfilePayload,
  SettingUpdateProfileForm,
  SettingUpdateAvatarPayload,
  SettingUpdateAvatarForm,
  SettingDeviceSession,
  SettingMfaSetupData,
  SettingMfaSetupPayload,
  SettingMfaVerifyPayload,
  SettingMfaDisablePayload,
  SettingMfaState,
  SettingTabKey,
  SettingTabOption,
  AuthVerifyEmailPayload,
  AuthVerifyEmailForm,
  AuthVerifyEmailResponse,
  AuthCreatePasswordPayload,
  AuthCreatePasswordForm,
  AuthForgotPasswordPayload,
  AuthForgotPasswordForm,
  AuthLoginForm,
  AuthLoginErrorResponse,
  AuthPreLoginResponse,
  AuthResendVerificationPayload,
  AuthResendVerificationForm,
  PasswordRequirement,
  AuthUser,
  AlertsCore,
  AuthCheckEmailResponse,
  ModulePermission,
  NotificationVariant,
  NotificationConnectionStatus,
  NotificationItem,
  NotificationCountResponse,
  NotificationPagedResponse,
  NotificationApiItem,
  IncomingNotificationPayload,
  NotificationPagedFilters,
  ValidationRule,
  ValidationOptions,
  ValidationTrigger,
}
