import type { CrmFeature, CrmStage, CrmStat } from './frontpage/crm'
import type {
  AlertsCore,
  AuthCheckEmailResponse,
  AuthCreatePasswordPayload,
  AuthCreatePasswordForm,
  AuthLoginPayload,
  AuthRegisterPayload,
  PasswordRequirement,
  AuthVerifyEmailResponse,
  AuthVerifyEmailPayload,
  AuthUser,
  ModulePermission,
} from './auth/auth.interface'
import type {
  IncomingNotificationPayload,
  NotificationApiItem,
  NotificationPagedFilters,
  NotificationCountResponse,
  NotificationConnectionStatus,
  NotificationPagedResponse,
  NotificationItem,
  NotificationVariant,
} from './notification/notification.interface'

export type {
  CrmFeature,
  CrmStage,
  CrmStat,
  AuthLoginPayload,
  AuthRegisterPayload,
  AuthVerifyEmailPayload,
  AuthVerifyEmailResponse,
  AuthCreatePasswordPayload,
  AuthCreatePasswordForm,
  PasswordRequirement,
  AuthUser,
  AlertsCore,
  AuthCheckEmailResponse,
  ModulePermission,
  NotificationVariant,
  NotificationConnectionStatus,
  NotificationItem,
  NotificationCountResponse,
  NotificationPagedResponse,
  NotificationApiItem,
  IncomingNotificationPayload,
  NotificationPagedFilters,
}
